Algoritmo "expressoes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/04/2021
Var
// Seção de Declarações das variáveis 
   exprA: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   exprA <- (18div1.5)-(1 * 5) -4 - (2 + 3 + 5) div 2
   escreval("Resposta é: ", exprA)
Fimalgoritmo