Algoritmo "primeiro_exercicio"
// Disciplina   : [Algoritmos e Programação]
// Descrição   : De acordo com os algoritmos a seguir escreva o código
//em portugol:
// Autor(a)    : Claudia Yapuchura
// Data atual  : 14/04/2021
Var
// Seção de Declarações das variáveis 
   x, y, z:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 1
   y <- 2
   
   z <- y-x
   
   x <- 5
   y <- x+z
   escreval("X: ", x, ", Y: ",y, ", Z: ",z)
Fimalgoritmo