Algoritmo "troca_valores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Troque os seus conteúdos fazendo com que o valor que está em
//A passe para B e vice-versa. Ao final, escrever os valores que ficaram arma-
//zenados nas variáveis
// Autor(a)    : Claudia Yapuchura
// Data atual  : 14/04/2021
Var
   a, b, c: inteiro
Inicio
   a <- 10
   b <- 20

   c <- a
   a <- b
   b <- c

   escreval("A: ",a, " B: ")
Fimalgoritmo